defaults:
  - net: byol
  - criterion: byol_negative_cosine_similarity
  - losses: default
  - metrics: sim_clr
  - .@linear_eval_cfg: stl10

_target_: src.models.byol_module.BYOLModule
feat_dim: ${feat_dim}
num_classes: ${num_classes}

optimizer:
  _target_: pl_bolts.optimizers.LARS
  _partial_: true
  lr: ${eval:'0.4 * ${data.batch_size} / 256'}
  momentum: 0.9
  weight_decay: 15e-7

scheduler:
  _target_: torchtune.modules.get_cosine_schedule_with_warmup
  _partial_: True
  num_warmup_steps: 10
  num_training_steps: ${eval:'${trainer.max_epochs} - 10'}

compile: false
