defaults:
  - net: resnet18_with_head
  - criterion: ce_loss
  - losses: default
  - metrics: mnist

_target_: src.models.baseline_module.BaselineLitModule

net:
  head:
    _target_: torch.nn.Linear
    in_features: 512
    out_features: ${num_classes}

optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  momentum: 0.9
  lr: 0.1
  weight_decay: 5e-4

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 40
  gamma: 0.2


# compile model for faster training with pytorch 2.0
compile: false
