# @package _global_

# runs with execution time profiling

defaults:
  - default

trainer:
  max_epochs: 1
  enable_checkpointing: False
  # profiler: "simple"
  # profiler: "advanced"
  profiler:
    _target_: pytorch_lightning.profilers.PyTorchProfiler
    on_trace_ready:
      _target_: torch.profiler.tensorboard_trace_handler
      dir_name: profiler_logs
    record_shapes: True
    profile_memory: True
    with_stack: True

