defaults:
  - encoder: resnet18

_target_: src.models.components.byol.BYOL

projection_head:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Linear
      in_features: 512
      out_features: 1024
    - _target_: torch.nn.BatchNorm1d
      num_features: 1024
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.Linear
      in_features: 1024
      out_features: 256

prediction_head:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Linear
      in_features: 256
      out_features: 1024
    - _target_: torch.nn.BatchNorm1d
      num_features: 1024
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.Linear
      in_features: 1024
      out_features: 256

num_steps: ${eval:'${dataset_length} / ${data.batch_size} * ${trainer.max_epochs}'}
momentum: 0.9995
