defaults:
  - .@net: resnet18

_target_: src.models.components.base.EncoderWithHead
encoder:
  _target_: src.models.components.wrappers.ModelConstructor
  modules:
    fc: torch.nn.Identity
head:
  _target_: torch.nn.Sequential
  _args_:
    - _target_: torch.nn.Linear
      in_features: 512
      out_features: ${eval:'${feat_dim} * 4'}
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.Linear
      in_features: ${eval:'${feat_dim} * 4'}
      out_features: ${feat_dim}
